### ISSUE TITLE
The plural of a dice is 'die'

### ISSUE THREAD

**Issue by AntoineDao** [riofriz/opf-bot#3]
Just being super obnoxious and correcting your english :gb:

[here](https://github.com/riofriz/opf-bot/tree/master/rpg/dices)

**Comment by riofriz** [comment]
Dear Antoine,
LOL.

**Comment by riofriz** [comment]
Dear Antoine,
I really want to help you with the issue, so help me understanding it properly.
Could you please link the file where this is happening and I'll make sure to fix it for you.
We care about our customer feedbacks!
Thanks for understanding,
Your bbbbbbboiiiii

**Comment by AntoineDao** [comment]
Closing this because I'm trying to clean up my endless list of open issues. I lol'd reading this again.
